# Generated by Django 2.0 on 2019-06-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190605_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-introduction_createtime']},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='introdution_createtime',
            new_name='introduction_createtime',
        ),
    ]
