# Generated by Django 2.0 on 2019-06-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='store_introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='store_opening_time',
            field=models.TextField(default=''),
        ),
    ]
