# Generated by Django 2.0 on 2019-06-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190605_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_p',
            new_name='store_phone',
        ),
    ]
