# Generated by Django 2.0 on 2019-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190605_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, height_field='store_image_height', null=True, upload_to='', width_field='store_image_width'),
        ),
    ]
