# Generated by Django 2.0 on 2019-06-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_image', models.ImageField(height_field='store_image_height', upload_to='', width_field='store_image_width')),
                ('store_image_width', models.IntegerField(default=0)),
                ('store_image_height', models.IntegerField(default=0)),
                ('store_p', models.CharField(max_length=13)),
                ('introdution_createtime', models.DateTimeField(verbose_name='date published')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
            ],
        ),
    ]
