# Generated by Django 2.0 on 2019-06-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('user_account', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
